############## General ############################################
server:
  port: 7777
###################################################################

############## Database ###########################################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth2-auth-server
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true

  flyway:
    baseline-on-migrate: true
    schemas: public
###################################################################
